"""HTML report generator that consolidates all backtest outputs."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

import pandas as pd


def _table_html(df: pd.DataFrame, title: str) -> str:
    """Render a dataframe section with heading and HTML table."""
    if df is None or df.empty:
        return f"<h3>{html.escape(title)}</h3><p>No data available.</p>"
    return (
        f"<h3>{html.escape(title)}</h3>"
        + df.to_html(index=False, classes="data-table", border=0)
    )


def _dict_table(payload: dict[str, Any], title: str) -> str:
    """Render a dictionary as a two-column key/value HTML table."""
    if not payload:
        return f"<h3>{html.escape(title)}</h3><p>No data available.</p>"
    rows = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td>{html.escape(str(v))}</td></tr>"
        for k, v in payload.items()
    )
    return (
        f"<h3>{html.escape(title)}</h3>"
        "<table class='data-table'><thead><tr><th>Metric</th><th>Value</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def build_html_report(
    summary_payload: dict[str, Any],
    trade_log_df: pd.DataFrame,
    monte_carlo_df: pd.DataFrame,
    output_path: str,
    entries_chart_path: str = "../charts/entries.png",
    equity_chart_path: str = "../charts/equity_curve.png",
) -> None:
    """Build a single-file HTML report with all backtest output data.

    Args:
        summary_payload: Summary payload generated by reporting layer.
        trade_log_df: Full trade log dataframe.
        monte_carlo_df: Full Monte Carlo scenario dataframe.
        output_path: Destination HTML path.
        entries_chart_path: Relative path to entry marker chart.
        equity_chart_path: Relative path to equity curve chart.
    """
    metrics = summary_payload.get("metrics", {})
    by_month = pd.DataFrame(summary_payload.get("win_rate_by_month", []))
    by_hour = pd.DataFrame(summary_payload.get("win_rate_by_hour", []))
    by_weekday = pd.DataFrame(summary_payload.get("win_rate_by_weekday", []))
    monte_carlo_stats = summary_payload.get("monte_carlo", {})

    raw_json = html.escape(json.dumps(summary_payload, indent=2, default=str))
    trades_count = 0 if trade_log_df is None else len(trade_log_df)
    mc_count = 0 if monte_carlo_df is None else len(monte_carlo_df)

    report_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>NAS100 IFVG Backtest Report</title>
  <style>
    body {{
      font-family: "Segoe UI", Tahoma, sans-serif;
      background: #f6f8fb;
      color: #1f2937;
      margin: 0;
      padding: 24px;
    }}
    .container {{
      max-width: 1400px;
      margin: 0 auto;
      background: #ffffff;
      border-radius: 12px;
      padding: 24px;
      box-shadow: 0 6px 24px rgba(0, 0, 0, 0.08);
    }}
    h1, h2, h3 {{
      margin-top: 0;
      color: #0f172a;
    }}
    .meta {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 12px;
      margin-bottom: 20px;
    }}
    .card {{
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
      padding: 12px;
    }}
    .charts {{
      display: grid;
      grid-template-columns: 1fr;
      gap: 18px;
      margin-bottom: 20px;
    }}
    .chart-box img {{
      width: 100%;
      border: 1px solid #dbe4f0;
      border-radius: 8px;
      background: #fff;
    }}
    .section {{
      margin-top: 22px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
    }}
    .data-table {{
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
      margin-bottom: 18px;
      font-size: 13px;
    }}
    .data-table th, .data-table td {{
      border: 1px solid #e5e7eb;
      padding: 8px 10px;
      text-align: left;
      white-space: nowrap;
    }}
    .data-table thead {{
      background: #eef2ff;
    }}
    details {{
      margin-top: 12px;
      background: #f8fafc;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 10px;
    }}
    pre {{
      white-space: pre-wrap;
      font-size: 12px;
      margin: 0;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>NAS100 IFVG Backtest Report</h1>
    <div class="meta">
      <div class="card"><strong>Total Trades</strong><br>{trades_count}</div>
      <div class="card"><strong>Monte Carlo Scenarios</strong><br>{mc_count}</div>
      <div class="card"><strong>Win Rate %</strong><br>{html.escape(str(metrics.get("win_rate_pct", "")))}</div>
      <div class="card"><strong>Total Return %</strong><br>{html.escape(str(metrics.get("total_return_pct", "")))}</div>
    </div>

    <div class="charts">
      <div class="chart-box">
        <h3>Entry Markers</h3>
        <img src="{html.escape(entries_chart_path)}" alt="Entries Chart" />
      </div>
      <div class="chart-box">
        <h3>Equity Curve</h3>
        <img src="{html.escape(equity_chart_path)}" alt="Equity Curve" />
      </div>
    </div>

    <div class="section">
      {_dict_table(metrics, "Performance Metrics")}
    </div>

    <div class="section">
      {_table_html(by_month, "Win Rate By Month")}
      {_table_html(by_hour, "Win Rate By Hour")}
      {_table_html(by_weekday, "Win Rate By Weekday")}
    </div>

    <div class="section">
      {_dict_table(monte_carlo_stats, "Monte Carlo Summary Stats")}
      {_table_html(monte_carlo_df, "Monte Carlo Scenarios (Full)")}
    </div>

    <div class="section">
      {_table_html(trade_log_df, "Trade Log (Full)")}
    </div>

    <div class="section">
      <details>
        <summary><strong>Raw Summary JSON</strong></summary>
        <pre>{raw_json}</pre>
      </details>
    </div>
  </div>
</body>
</html>
"""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report_html, encoding="utf-8")

